<a href="https://colab.research.google.com/github/dhanunjay-123/Quicks_Delivery/blob/main/Numpy_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hi")

hi


1D array

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = a
print(b)

[1 2 3]


2D array


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


3D array

In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(Numpy_zeroes)

In [ ]:
import numpy as np
a = np.zeros((1,2))
print(a)

[[0. 0.]]


In [ ]:
import numpy as np
a = np.zeros((3,2,2))
print(a)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [ ]:
import numpy as np
a = np.ones((3,2,2))
print(a)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


Np eye means matrix

In [ ]:
import numpy as np
a = np.eye((2))
print(a)

[[1. 0.]
 [0. 1.]]


range we use np.range(numbers)

In [ ]:
import numpy as np
a = np.arange(10,50,2)
print(a)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
import numpy as np
arr = np.array([20,10,40,39])
print(arr[-3:-1])

[10 40]


:: difference between :

In [ ]:
import numpy as np
arr = np.array([20,10,40,39])
print(arr[-3::-1])

[10 20]


In [ ]:
import numpy as np
a = np.array([10,16])
b = np.array([30,7])
print("adding ",a+b)
print("subracting ",a-b)
print("multiplying ", a*b)

adding  [40 23]
subracting  [-20   9]
multiplying  [300 112]


In [ ]:
import numpy as np
a = np.array([10,20,30,40,50,60])
print(a[a>25])

[30 40 50 60]


In [ ]:
import numpy as np
a= np.array([[1,3,5],[4,9,6]])
print(a.reshape(1,6))

[[1 3 5 4 9 6]]


In [ ]:
import numpy as np
a= np.array([[1,3,5],[4,9,6]])
print(a.reshape(2,3))

[[1 3 5]
 [4 9 6]]


In [ ]:
import numpy as np
a= np.array([[1,3,5],[4,9,6]])
print(a.flatten())

[1 3 5 4 9 6]


Borh Transpore using keyword .T and vs stack(a,b)

In [ ]:
import numpy as np
a= np.array([[1,3,5],[4,9,6]])
print(a.T)

[[1 4]
 [3 9]
 [5 6]]


In [ ]:
import numpy as np
a= np.array([1,3,5])
b = np.array([2,3,4])
print(np.vstack((a,b)))

[[1 3 5]
 [2 3 4]]


Repeat

In [3]:
import numpy as np
print(np.repeat([1,3],4))

[1 1 1 1 3 3 3 3]


In [7]:
import numpy as np
arr = np.array([1,2,4])
print(np.repeat(arr,4))

[1 1 1 1 2 2 2 2 4 4 4 4]


unique

In [4]:
import numpy as np
arr = np.array([2,2,4,6,7,7,8])
print(np.unique(arr))

[2 4 6 7 8]


In [12]:
import numpy as np
arr = np.array([4,7,19])
print((4<arr)&(arr<19))

[False  True False]


checking how many dimensions using this .ndim
same length should have


In [3]:
import numpy as np
a = np.array([[1,2,3,4],[7,8,9,0]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(d.ndim)

2
3
